version: '3.9'

services:
  backend:
    build: .
    ports:
      - "127.0.0.1:8500:8500"
    volumes: 
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      -DOCKER_ENABLE: DOCKER
 
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: asc_dev
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 127.0.0.1:60306:3306

